
name: caller-workflow
on: workflow_dispatch

jobs:
  demo:
    name: any-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.9
    - run: |
        python -c print("It's a caller workflow")
        djkbd 
        python -c print("I will call the called workflow")
