name: called-workflow
on: 
  workflow_run:
    workflows: ["caller-workflow"]
    types: ["completed"]
jobs:
  demo:
    name: demo-job
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.9
      - run: |
          python -c "print(\"I am a Called workflow\")"
          python -c "print(\"The Caller has called me\")"
